.TH "main.c" 3 "4 Dec 2009" "Version 0.1.0" "precorderD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include 'TPS6105X.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.SH "Author"
.PP 
Generated automatically by Doxygen for precorderD from the source code.
