.TH "TPS6105X_t" 3 "4 Dec 2009" "Version 0.1.0" "precorderD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPS6105X_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TPS6105X.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBoptions\fP [8][12]"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char \fBTPS6105X_t::options\fP[8][12]"
.SS "int \fBTPS6105X_t::value\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for precorderD from the source code.
